service: drinkaid-insights

provider:
  name: aws
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  runtime: python3.9
  stage: dev
  region: ap-southeast-1

functions:
  meta:
    handler: metaHandler.meta
    timeout: 30
    events:
      - http:
          path: meta
          method: post

  analyze:
    handler: analysisHandler.analyze
    timeout: 60
    events:
      - http:
          path: analyze
          method: post

package:
  include:
    - modules/postal_coord_map.csv

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 18000
    lambdaTimeout: 60

